/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Zapcode {
  constructor(code: string, options?: ZapcodeOptions | undefined | null)
  /**
   * Run the code to completion. Returns the output value and captured stdout.
   *
   * If the code calls an external function, this will return an error.
   * Use `start()` for code that may suspend.
   */
  run(inputs?: Record<string, any> | undefined | null): ZapcodeResult
  /**
   * Start execution. Returns either a completed result or a suspension.
   *
   * Check the `completed` field to determine which type was returned.
   */
  start(inputs?: Record<string, any> | undefined | null): ZapcodeResult | ZapcodeSuspension
}

export declare class ZapcodeSessionHandle {
  static create(options?: ZapcodeSessionOptions | undefined | null): ZapcodeSessionHandle
  static load(bytes: Buffer): ZapcodeSessionHandle
  dump(): Buffer
  runChunk(code: string, inputs?: Record<string, any> | undefined | null): ZapcodeSessionResult | ZapcodeSessionSuspension
  resume(returnValue: any): ZapcodeSessionResult | ZapcodeSessionSuspension
}

export declare class ZapcodeSnapshotHandle {
  /** Serialize the snapshot to bytes for storage or transport. */
  dump(): Buffer
  /** Load a snapshot from bytes previously obtained via `dump()`. */
  static load(bytes: Buffer): ZapcodeSnapshotHandle
  /**
   * Resume execution with the return value from the external function.
   *
   * Returns either a `ZapcodeResult` (complete) or a `ZapcodeSuspension`
   * (suspended again on another external call).
   */
  resume(returnValue: any): ZapcodeResult | ZapcodeSuspension
}

export interface JsTraceSpan {
  name: string
  startTimeMs: number
  endTimeMs: number
  durationUs: number
  status: string
  attributes: Array<Array<string>>
  children: Array<JsTraceSpan>
}

export interface ZapcodeOptions {
  /** Variable names injected at runtime. */
  inputs?: Array<string>
  /** Function names the sandbox may call. */
  externalFunctions?: Array<string>
  /** Memory limit in megabytes (default: 32). */
  memoryLimitMb?: number
  /** Execution time limit in milliseconds (default: 5000). */
  timeLimitMs?: number
}

export interface ZapcodeResult {
  /** Whether execution completed. Always true for this type. */
  completed: boolean
  /** The output value, converted to a JSON-compatible serde_json::Value. */
  output: any
  /** Captured stdout output. */
  stdout: string
  /** Execution trace (parse → compile → execute). */
  trace: JsTraceSpan
}

export interface ZapcodeSessionOptions {
  /** Function names the sandbox may call. */
  externalFunctions?: Array<string>
  /** Memory limit in megabytes (default: 32). */
  memoryLimitMb?: number
  /** Execution time limit in milliseconds (default: 5000). */
  timeLimitMs?: number
}

export interface ZapcodeSessionResult {
  /** Whether execution completed. Always true for this type. */
  completed: boolean
  /** The output value, converted to a JSON-compatible serde_json::Value. */
  output: any
  /** Captured stdout output for this chunk/resume step. */
  stdout: string
  /** Opaque session bytes -- pass to `ZapcodeSessionHandle.load()` to continue. */
  session: Buffer
}

export interface ZapcodeSessionSuspension {
  /** Whether execution completed. Always false for this type. */
  completed: boolean
  /** Name of the external function that caused suspension. */
  functionName: string
  /** Arguments passed to the external function. */
  args: Array<any>
  /** Captured stdout output for this chunk/resume step. */
  stdout: string
  /** Opaque session bytes -- pass to `ZapcodeSessionHandle.load()` to continue. */
  session: Buffer
}

export interface ZapcodeSuspension {
  /** Whether execution completed. Always false for this type. */
  completed: boolean
  /** Name of the external function that caused suspension. */
  functionName: string
  /** Arguments passed to the external function. */
  args: Array<any>
  /** Opaque snapshot bytes -- pass to `ZapcodeSnapshotHandle.load()` to resume. */
  snapshot: Buffer
}
